### PR TITLE
Add support for flatmap

### LINKED ISSUE #11: flatMap doesn't work
Calling flatMap on a List doesn't work. Can get around it by just doing a map then a flatten.

```
var {Record, List} = require("typed-immutable")
var Item = Record({
    ids: List(Number)
});

var Items = List(Item);
var a = new Item({ids: [1,2,3,4]})
var b = new Item({ids: [5,6]})
var items = new Items([a, b])

// Array [1, 2, 3, 4, 5, 6]
items.map(item => item.ids).flatten().toJS(); 
// doesn't work
// TypeError: Invalid value: Invalid data structure "1" was passed to Typed.Record({ids: Typed.List(Number)})
items.flatMap(item => item.ids).toJS()

// Using immutable List directly works
var immutable = require('immutable');
items = immutable.List([a,b]);
// Array [1, 2, 3, 4, 5, 6]
items.flatMap(item => item.ids).toJS()
```

### PR DESCRIPTION
**Pull request by davecoates**
Resolves #11

### CODE REVIEW

**Comment by Gozala** [comment]
Unfortunately I am no longer able to maintain this project, I apologize. If someone wishes to step up and take leadership of this project please respond to #21

**Comment by stutrek** [comment]
👍 do others like it? @lukesneeringer or @udnisap

**Comment by lukesneeringer** [comment]
Looks good to me.

**Comment by lukesneeringer** [comment]
@davecoates Can you merge master into this branch and push so Travis can pick it up?

**Comment by davecoates** [comment]
👍

**Comment by lukesneeringer** [comment]
@davecoates Still need `master` merged in before I can merge. As soon as GitHub gives me a green button, I am ready to hit it. :-)

**Comment by davecoates** [comment]
Sorry! Was too early for me... forgot to actually fetch from upstream first

**Comment by lukesneeringer** [comment]
And sadly, since I just merged your other one...now you have to do it again.

**Comment by davecoates** [comment]
... and done!

**Comment by lukesneeringer** [comment]
:tada:

**Pull request merged**
