### PR TITLE
Build setup

### PR DESCRIPTION
**Pull request by udnisap**
Can the travis.ci integration I requested from the repo owner approved or can you add me to the management group?
We can use ci to test like  https://github.com/udnisap/typed-immutable/pull/1

@stutrek @davecoates

### CODE REVIEW

**Comment by udnisap** [comment]
Can the travis.ci integration can be approved or can you add me to the management group?
We can use ci to test like  https://github.com/udnisap/typed-immutable/pull/1

**Comment by stutrek** [comment]
Awesome. Does this/do you know how to fix the automated tests that used to run on each PR?

**Comment by udnisap** [comment]
i need permission to add this to repo

**Comment by stutrek** [comment]
Sorry, I thought write access was enough. You have admin now.

**Comment by udnisap** [comment]
I think you need to manually approve it. It says
'Access request pending@typed-immutable'

**Comment by stutrek** [comment]
does this need to be configured first? Do we need to merge this and configure it at the same time? https://github.com/typed-immutable/typed-immutable/settings/hooks/4507717

You have admin on this repo, do whatever you need to do.

**Comment by stutrek** [comment]
@udnisap do you know where the button I need to press is? Is it even on github?

**Comment by lukesneeringer** [comment]
If you will make me an admin, I will figure it out. I have done this before.

**Comment by lukesneeringer** [comment]
Actually, I would need to be an owner, turns out. (I am already an admin.)

**Comment by stutrek** [comment]
You're an owner... LMK what it was.

**Comment by lukesneeringer** [comment]
Access is granted. It was under "OAuth applications".
I am going to do the rest of this setup.

**Pull request merged**
